version: '2'
services:
  web:
    build: .docker/web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/drupal

  db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - "3306:3306"
    volumes:
      - .docker/runtime/data:/var/lib/mysql
    #  - .docker/db-init:/docker-entrypoint-initdb.d # Place init .sql file(s) in the .docker/db-init folder.

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - 8000:80

#  solr:
#    image: solr:5.5-alpine
#    volumes:
#      - .docker-runtime/solr:/opt/solr/server/solr/mycores
#    entrypoint:
#      - docker-entrypoint.sh
#      - solr-precreate
#      - main
#    ports:
#      - "8001:8983"

#  mailhog:
#    image: mailhog/mailhog
#    ports:
#      - "8002:8025"

#  redis:
#    image: redis:3.2-alpine

#  memcached:
#    image: memcached:1.4-alpine

#  memcached-admin:
#    image: phynias/phpmemcachedadmin
#    ports:
#      - "8003:80"

#  varnish:
#    image: wodby/drupal-varnish
#    depends_on:
#      - nginx
#    environment:
#      VARNISH_SECRET: secret
#      VARNISH_BACKEND_HOST: nginx
#      VARNISH_BACKEND_PORT: 80
#      VARNISH_MEMORY_SIZE: 256M
#      VARNISH_STORAGE_SIZE: 1024M
#    ports:
#      - "8004:6081" # HTTP Proxy
#      - "8005:6082" # Control terminal

#  sshd:
#    image: wodby/drupal-sshd
#    environment:
#      SSH_PUB_KEY: "ssh-rsa ..."
#    volumes_from:
#      - php
#    ports:
#      - "8006:22"
